# .streamlite/secrets.toml
[connections.snowflake]
account = "TXZACDP-WF08144"
user = "RIATRAIL"
password = "NowTimeForSnow7@"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
